### ISSUE TITLE
GetEndpointsWithOnOffAsync - nullReferenceException

### ISSUE THREAD

**Issue by nicolascastel** [leonmeijer/Zipato.NET#1]
Hi,
The config of endpoints is never instanciate. (Null Reference Exception on a toList() operation). So, I modify the return of your function : (no filter on e.config.Hidden).
                      //return onOffEndpoints.Where(e => !e.Config.Hidden) ;
                      return onOffEndpoints;
(Sorry for my english...)

**Comment by leonmeijer** [comment]
For all the found endpoints (in onOffEndpoints), it's doing a REST call to /endpoint/UUID?config=true. Perhaps one of your endpoints doesn't return a value. I changed my code. I'm doing now

``` C#
return onOffEndpoints.Where(e=> e.Config == null || !e.Config.Hidden);
```

**Comment by nicolascastel** [comment]
Thanks, 
the REST  "/endpoint/UUID?config=true" called only if hideHidden == true. So if hideHidden = false, e.config is always null.

**Comment by leonmeijer** [comment]
You're right, that was a bug. It's now fixed, i'm closing this issue.
